"use client"

// Domain-specific skill sets - expanded with more categories
const domainSkills = {
  "network engineer": [
    { name: "router", description: "Network device that forwards data packets between computer networks" },
    { name: "switch", description: "Network device that connects devices on a computer network" },
    {
      name: "firewall",
      description: "Network security device that monitors and filters incoming and outgoing network traffic",
    },
    { name: "CCNA", description: "Cisco Certified Network Associate certification" },
    { name: "CCNP", description: "Cisco Certified Network Professional certification" },
    { name: "CCIE", description: "Cisco Certified Internetwork Expert certification" },
    { name: "Cisco", description: "Leading networking equipment manufacturer" },
    { name: "Juniper", description: "Network equipment manufacturer specializing in routing and switching" },
    { name: "load balancer", description: "Device that distributes network traffic across multiple servers" },
    { name: "VPN", description: "Virtual Private Network for secure connections" },
    { name: "OSPF", description: "Open Shortest Path First routing protocol" },
    { name: "BGP", description: "Border Gateway Protocol for internet routing" },
    { name: "MPLS", description: "Multiprotocol Label Switching for high-performance networks" },
    { name: "SDN", description: "Software-Defined Networking" },
    { name: "network automation", description: "Tools and processes to automate network operations" },
    { name: "Wireshark", description: "Network protocol analyzer" },
    { name: "Tcpdump", description: "Command-line packet analyzer" },
    { name: "VLAN", description: "Virtual Local Area Network" },
    { name: "subnetting", description: "Dividing networks into subnetworks" },
    { name: "IPv6", description: "Internet Protocol version 6" },
    { name: "QoS", description: "Quality of Service for network traffic prioritization" },
  ],
  "cyber security": [
    { name: "NIST", description: "National Institute of Standards and Technology framework" },
    { name: "penetration testing", description: "Method of evaluating security by simulating attacks" },
    { name: "vulnerability assessment", description: "Process of identifying security vulnerabilities" },
    { name: "SIEM", description: "Security Information and Event Management" },
    { name: "SOC", description: "Security Operations Center" },
    { name: "incident response", description: "Organized approach to addressing security breaches" },
    { name: "threat hunting", description: "Proactively searching for cyber threats" },
    { name: "CISSP", description: "Certified Information Systems Security Professional" },
    { name: "CEH", description: "Certified Ethical Hacker certification" },
    { name: "ISO 27001", description: "Information security management standard" },
    { name: "zero trust", description: "Security model that requires verification for all users" },
    { name: "malware analysis", description: "Process of studying malicious software" },
    { name: "OSCP", description: "Offensive Security Certified Professional" },
    { name: "SANS", description: "Information security training organization" },
    { name: "GIAC", description: "Global Information Assurance Certification" },
    { name: "CISM", description: "Certified Information Security Manager" },
    { name: "CISA", description: "Certified Information Systems Auditor" },
    { name: "IDS/IPS", description: "Intrusion Detection/Prevention Systems" },
    { name: "endpoint security", description: "Security approach focusing on end-user devices" },
    { name: "DLP", description: "Data Loss Prevention" },
    { name: "red team", description: "Group that simulates attacks to test security" },
    { name: "blue team", description: "Group that defends against cyber attacks" },
    { name: "forensics", description: "Analysis of security incidents and data breaches" },
  ],
  "software developer": [
    { name: "JavaScript", description: "Programming language for web development" },
    { name: "TypeScript", description: "Typed superset of JavaScript" },
    { name: "React", description: "JavaScript library for building user interfaces" },
    { name: "Angular", description: "TypeScript-based web application framework" },
    { name: "Vue.js", description: "JavaScript framework for building user interfaces" },
    { name: "Node.js", description: "JavaScript runtime built on Chrome's V8 JavaScript engine" },
    { name: "Python", description: "High-level programming language" },
    { name: "Java", description: "Object-oriented programming language" },
    { name: "C#", description: "Programming language developed by Microsoft" },
    { name: "SQL", description: "Structured Query Language for managing databases" },
    { name: "NoSQL", description: "Database that provides a mechanism for storage and retrieval of data" },
    { name: "Git", description: "Distributed version control system" },
    { name: "CI/CD", description: "Continuous Integration and Continuous Deployment" },
    { name: "Agile", description: "Software development methodology" },
    { name: "Scrum", description: "Agile framework for managing work" },
    { name: "RESTful API", description: "Architectural style for distributed systems" },
    { name: "GraphQL", description: "Query language and runtime for APIs" },
    { name: "Docker", description: "Platform for containerized applications" },
    { name: "Kubernetes", description: "Container orchestration platform" },
    { name: "AWS", description: "Amazon Web Services cloud platform" },
    { name: "Azure", description: "Microsoft cloud computing service" },
    { name: "GCP", description: "Google Cloud Platform" },
    { name: "microservices", description: "Software architecture style" },
    { name: "TDD", description: "Test-Driven Development methodology" },
    { name: "Redux", description: "State management library for JavaScript" },
    { name: "Spring Boot", description: "Java-based framework for microservices" },
    { name: "Ruby on Rails", description: "Web application framework" },
    { name: "Django", description: "Python web framework" },
    { name: "Express", description: "Web framework for Node.js" },
  ],
  "data scientist": [
    { name: "machine learning", description: "Field of AI focused on building systems that learn from data" },
    { name: "deep learning", description: "Subset of machine learning using neural networks" },
    { name: "Python", description: "Programming language commonly used in data science" },
    { name: "R", description: "Programming language for statistical computing" },
    { name: "TensorFlow", description: "Open-source machine learning framework" },
    { name: "PyTorch", description: "Open-source machine learning library" },
    { name: "SQL", description: "Language for managing and querying databases" },
    { name: "data visualization", description: "Graphical representation of information and data" },
    { name: "statistical analysis", description: "Collection and interpretation of data" },
    { name: "Pandas", description: "Data manipulation and analysis library" },
    { name: "NumPy", description: "Library for numerical computations" },
    { name: "Jupyter", description: "Web application for creating and sharing documents with live code" },
    { name: "scikit-learn", description: "Machine learning library for Python" },
    { name: "SAS", description: "Software suite for advanced analytics" },
    { name: "SPSS", description: "Statistical software package" },
    { name: "data mining", description: "Process of discovering patterns in large datasets" },
    { name: "NLP", description: "Natural Language Processing" },
    { name: "computer vision", description: "Field of AI that enables computers to interpret visual information" },
    { name: "feature engineering", description: "Process of selecting and transforming variables for models" },
    { name: "A/B testing", description: "Method of comparing two versions of something" },
    { name: "Hadoop", description: "Framework for distributed storage and processing" },
    { name: "Spark", description: "Unified analytics engine for big data processing" },
    { name: "big data", description: "Data sets too large for traditional data processing" },
    { name: "time series analysis", description: "Analysis of data points collected over time" },
    { name: "regression", description: "Statistical method for modeling relationships" },
    { name: "classification", description: "Machine learning task of categorizing data" },
    { name: "clustering", description: "Grouping similar data points together" },
  ],
  "devops engineer": [
    { name: "Docker", description: "Platform for developing, shipping, and running applications in containers" },
    { name: "Kubernetes", description: "Container orchestration system" },
    { name: "AWS", description: "Amazon Web Services cloud platform" },
    { name: "Azure", description: "Microsoft's cloud computing service" },
    { name: "GCP", description: "Google Cloud Platform" },
    { name: "Terraform", description: "Infrastructure as code software tool" },
    {
      name: "Ansible",
      description: "Open-source software provisioning, configuration management, and application-deployment tool",
    },
    { name: "Jenkins", description: "Open-source automation server" },
    { name: "CI/CD", description: "Continuous Integration and Continuous Deployment" },
    { name: "Git", description: "Distributed version control system" },
    { name: "monitoring", description: "Observing and checking the progress or quality of something over time" },
    { name: "logging", description: "Recording of events in a system" },
    { name: "ELK stack", description: "Elasticsearch, Logstash, and Kibana for log management" },
    { name: "Prometheus", description: "Monitoring and alerting toolkit" },
    { name: "Grafana", description: "Analytics and monitoring platform" },
    { name: "GitLab", description: "Web-based DevOps lifecycle tool" },
    { name: "GitHub Actions", description: "CI/CD platform from GitHub" },
    { name: "ArgoCD", description: "Declarative, GitOps continuous delivery tool for Kubernetes" },
    { name: "Helm", description: "Package manager for Kubernetes" },
    { name: "IaC", description: "Infrastructure as Code" },
    { name: "microservices", description: "Architectural approach for building applications" },
    { name: "Linux", description: "Open-source operating system" },
    { name: "shell scripting", description: "Writing scripts for shell interpreters" },
    { name: "Chef", description: "Configuration management tool" },
    { name: "Puppet", description: "Configuration management tool" },
    { name: "SRE", description: "Site Reliability Engineering" },
  ],
  "cloud architect": [
    { name: "AWS", description: "Amazon Web Services cloud platform" },
    { name: "Azure", description: "Microsoft's cloud computing service" },
    { name: "GCP", description: "Google Cloud Platform" },
    { name: "multi-cloud", description: "Using services from multiple cloud providers" },
    { name: "cloud migration", description: "Process of moving applications to the cloud" },
    { name: "serverless", description: "Cloud computing execution model" },
    { name: "IaaS", description: "Infrastructure as a Service" },
    { name: "PaaS", description: "Platform as a Service" },
    { name: "SaaS", description: "Software as a Service" },
    { name: "CloudFormation", description: "AWS service for infrastructure as code" },
    { name: "ARM templates", description: "Azure Resource Manager templates" },
    { name: "cloud security", description: "Policies and technologies to protect cloud data" },
    { name: "FinOps", description: "Cloud financial management discipline" },
    { name: "cost optimization", description: "Strategies to reduce cloud spending" },
    { name: "high availability", description: "System design approach to ensure uptime" },
    { name: "disaster recovery", description: "Tools and processes for recovering from failures" },
    { name: "AWS Well-Architected", description: "Framework for building secure, efficient systems" },
    { name: "hybrid cloud", description: "Mix of on-premises and cloud infrastructure" },
    { name: "VPC", description: "Virtual Private Cloud" },
    { name: "cloud native", description: "Building applications specifically for cloud environments" },
    { name: "Terraform", description: "Infrastructure as code software tool" },
    { name: "containers", description: "Lightweight, portable computing environments" },
  ],
  "product manager": [
    { name: "product roadmap", description: "Strategic document outlining the vision and direction of a product" },
    { name: "user stories", description: "Description of a feature from an end-user perspective" },
    { name: "agile", description: "Iterative approach to project management and product development" },
    { name: "scrum", description: "Framework for managing complex product development" },
    { name: "kanban", description: "Visual workflow management method" },
    {
      name: "sprint planning",
      description: "Event in scrum that defines what can be delivered in the upcoming sprint",
    },
    { name: "backlog grooming", description: "Process of reviewing, refining and prioritizing product backlog items" },
    { name: "MVP", description: "Minimum Viable Product - version of a product with just enough features" },
    { name: "A/B testing", description: "Method of comparing two versions of a webpage or app" },
    { name: "user research", description: "Process of understanding user behaviors, needs, and motivations" },
    { name: "competitive analysis", description: "Identifying competitors and evaluating their strategies" },
    { name: "KPI", description: "Key Performance Indicator - measurable value that demonstrates effectiveness" },
    { name: "OKR", description: "Objectives and Key Results - goal-setting framework" },
    { name: "market research", description: "Process of gathering information about target markets and customers" },
    { name: "product analytics", description: "Data collection and analysis of user behavior" },
    { name: "wireframing", description: "Creating a visual guide that represents the skeletal framework of a product" },
    { name: "prototyping", description: "Early sample or model built to test a concept or process" },
    { name: "user journey", description: "Path a user takes when interacting with a product" },
    { name: "persona", description: "Fictional character created to represent a user type" },
    { name: "stakeholder management", description: "Process of managing relationships with stakeholders" },
  ],
  "ux designer": [
    { name: "user research", description: "Process of understanding user behaviors, needs, and motivations" },
    { name: "wireframing", description: "Creating a visual guide that represents the skeletal framework of a product" },
    { name: "prototyping", description: "Early sample or model built to test a concept or process" },
    { name: "usability testing", description: "Evaluating a product by testing it with representative users" },
    { name: "information architecture", description: "Organization and structure of content in a product" },
    {
      name: "user journey mapping",
      description: "Visualizing the process that a user goes through to accomplish a goal",
    },
    { name: "interaction design", description: "Design of the interaction between users and products" },
    { name: "visual design", description: "Strategic use of design elements like colors, shapes, and typography" },
    { name: "accessibility", description: "Design that enables people with disabilities to use products" },
    {
      name: "responsive design",
      description: "Approach to web design that makes pages render well on various devices",
    },
    { name: "Figma", description: "Cloud-based design and prototyping tool" },
    { name: "Sketch", description: "Digital design app for macOS" },
    { name: "Adobe XD", description: "Vector-based user experience design tool" },
    { name: "InVision", description: "Digital product design platform" },
    { name: "heuristic evaluation", description: "Method for finding usability problems in a user interface design" },
    { name: "card sorting", description: "Method used to help design or evaluate information architecture" },
    { name: "A/B testing", description: "Method of comparing two versions of a webpage or app" },
    { name: "design thinking", description: "Methodology for creative problem solving" },
    { name: "user-centered design", description: "Design approach that focuses on users and their needs" },
    { name: "design system", description: "Collection of reusable components guided by standards" },
  ],
  "data engineer": [
    { name: "ETL", description: "Extract, Transform, Load - process of combining data from multiple sources" },
    { name: "data warehouse", description: "System for reporting and data analysis" },
    { name: "data lake", description: "Storage repository that holds a vast amount of raw data" },
    { name: "SQL", description: "Structured Query Language for managing relational databases" },
    {
      name: "NoSQL",
      description: "Database that provides a mechanism for storage and retrieval of non-relational data",
    },
    { name: "Apache Spark", description: "Unified analytics engine for big data processing" },
    { name: "Apache Kafka", description: "Distributed event streaming platform" },
    { name: "Apache Hadoop", description: "Framework for distributed storage and processing of big data" },
    { name: "Apache Airflow", description: "Platform to programmatically author, schedule and monitor workflows" },
    { name: "Python", description: "Programming language commonly used in data engineering" },
    { name: "Scala", description: "Programming language that combines object-oriented and functional programming" },
    { name: "Java", description: "Object-oriented programming language" },
    { name: "data modeling", description: "Process of creating a data model for storing data in a database" },
    { name: "data pipeline", description: "Series of data processing steps" },
    { name: "data governance", description: "Management of data availability, usability, integrity, and security" },
    { name: "data quality", description: "Measure of data's condition" },
    { name: "Snowflake", description: "Cloud-based data warehousing platform" },
    { name: "AWS Redshift", description: "Fully managed, petabyte-scale data warehouse service" },
    { name: "Google BigQuery", description: "Fully-managed, serverless data warehouse" },
    {
      name: "Azure Synapse",
      description: "Analytics service that brings together data integration, enterprise data warehousing",
    },
    { name: "dbt", description: "Data build tool for transforming data in warehouses" },
    { name: "data mesh", description: "Decentralized sociotechnical approach to data management" },
  ],
  "frontend developer": [
    { name: "HTML", description: "HyperText Markup Language - standard markup language for web pages" },
    { name: "CSS", description: "Cascading Style Sheets - style sheet language for styling web pages" },
    { name: "JavaScript", description: "Programming language for web development" },
    { name: "TypeScript", description: "Typed superset of JavaScript" },
    { name: "React", description: "JavaScript library for building user interfaces" },
    { name: "Angular", description: "TypeScript-based web application framework" },
    { name: "Vue.js", description: "Progressive JavaScript framework for building user interfaces" },
    { name: "Svelte", description: "Component framework that compiles at build time" },
    { name: "Redux", description: "State management library for JavaScript applications" },
    { name: "MobX", description: "State management library for JavaScript applications" },
    { name: "Webpack", description: "Static module bundler for JavaScript applications" },
    { name: "Vite", description: "Next generation frontend tooling" },
    { name: "Babel", description: "JavaScript compiler" },
    { name: "ESLint", description: "Tool for identifying and reporting on patterns in JavaScript" },
    { name: "Jest", description: "JavaScript testing framework" },
    { name: "Cypress", description: "End-to-end testing framework" },
    { name: "Storybook", description: "Tool for developing UI components in isolation" },
    { name: "Sass", description: "CSS preprocessor" },
    { name: "Less", description: "CSS preprocessor" },
    { name: "Tailwind CSS", description: "Utility-first CSS framework" },
    { name: "Bootstrap", description: "CSS framework for responsive, mobile-first front-end development" },
    { name: "Material UI", description: "React components for faster and easier web development" },
    {
      name: "responsive design",
      description: "Approach to web design that makes pages render well on various devices",
    },
    {
      name: "progressive web app",
      description: "Web app that uses modern web capabilities to deliver an app-like experience",
    },
  ],
}

// US Visa Types with detailed information - expanded with all visa types
const visaTypes = {
  work: [
    {
      type: "H-1B",
      name: "Specialty Occupation Workers",
      description: "For professionals in specialty occupations requiring at least a bachelor's degree",
      duration: "Initial 3 years, extendable up to 6 years total",
      sponsorship: "Employer must petition",
      dependents: "H-4 visa for spouse and unmarried children under 21",
    },
    {
      type: "L-1",
      name: "Intracompany Transferees",
      description:
        "For managers, executives (L-1A) or specialized knowledge employees (L-1B) transferring within a company",
      duration: "L-1A: Up to 7 years, L-1B: Up to 5 years",
      sponsorship: "Employer must petition",
      dependents: "L-2 visa for spouse and unmarried children under 21",
    },
    {
      type: "O-1",
      name: "Individuals with Extraordinary Ability",
      description: "For people with extraordinary ability in sciences, arts, education, business, or athletics",
      duration: "Initially up to 3 years, then 1-year extensions",
      sponsorship: "Employer must petition",
      dependents: "O-3 visa for spouse and unmarried children under 21",
    },
    {
      type: "TN",
      name: "NAFTA/USMCA Professionals",
      description:
        "For Canadian and Mexican citizens in professional occupations specified under USMCA (formerly NAFTA)",
      duration: "Up to 3 years, renewable indefinitely",
      sponsorship: "Self-petition at port of entry (Canadians) or consulate (Mexicans)",
      dependents: "TD visa for spouse and unmarried children under 21",
    },
    {
      type: "E-3",
      name: "Australian Specialty Occupation Workers",
      description: "Similar to H-1B but exclusively for Australian citizens",
      duration: "2 years, renewable indefinitely",
      sponsorship: "Employer must offer position",
      dependents: "E-3D visa for spouse and unmarried children under 21",
    },
    {
      type: "H-2A",
      name: "Temporary Agricultural Workers",
      description: "For seasonal agricultural workers",
      duration: "Up to 3 years",
      sponsorship: "Employer petition",
      dependents: "H-4 visa for spouse and unmarried children under 21",
    },
    {
      type: "H-2B",
      name: "Temporary Non-Agricultural Workers",
      description: "For seasonal non-agricultural workers",
      duration: "Up to 3 years",
      sponsorship: "Employer petition",
      dependents: "H-4 visa for spouse and unmarried children under 21",
    },
    {
      type: "P-1",
      name: "Athletes and Entertainers",
      description: "For internationally recognized athletes and entertainment groups",
      duration: "Up to 5 years for athletes, 1 year for entertainment groups",
      sponsorship: "Employer petition",
      dependents: "P-4 visa for spouse and unmarried children under 21",
    },
    {
      type: "R-1",
      name: "Religious Workers",
      description: "For ministers and religious workers",
      duration: "Up to 5 years",
      sponsorship: "Sponsoring religious organization",
      dependents: "R-2 visa for spouse and unmarried children under 21",
    },
    {
      type: "I",
      name: "Representatives of Foreign Media",
      description: "For representatives of foreign press, radio, film, or other media",
      duration: "Duration of assignment",
      sponsorship: "Media organization",
      dependents: "I visa for spouse and unmarried children under 21",
    },
  ],
  business: [
    {
      type: "E-1",
      name: "Treaty Traders",
      description: "For individuals conducting substantial trade between the US and their country",
      duration: "2 years initially, renewable indefinitely",
      sponsorship: "Self-sponsorship or company sponsorship",
      dependents: "E-1 visa for spouse and unmarried children under 21",
    },
    {
      type: "E-2",
      name: "Treaty Investors",
      description: "For investors who have made substantial investment in a US business",
      duration: "2 years initially, renewable indefinitely",
      sponsorship: "Self-sponsorship or company sponsorship",
      dependents: "E-2 visa for spouse and unmarried children under 21",
    },
    {
      type: "B-1",
      name: "Business Visitors",
      description: "For short-term business activities like negotiations, conferences, etc.",
      duration: "Up to 6 months, possible extension",
      sponsorship: "Self-sponsorship",
      dependents: "Family members need separate visas",
    },
    {
      type: "E-5",
      name: "Treaty Investors (EB-5)",
      description: "For investors making significant investments in US businesses that create jobs",
      duration: "Conditional permanent residence for 2 years, then permanent",
      sponsorship: "Self-petition",
      dependents: "Spouse and unmarried children under 21 included",
    },
  ],
  student: [
    {
      type: "F-1",
      name: "Academic Students",
      description: "For full-time students at accredited academic institutions",
      duration: "Duration of study program + optional practical training",
      sponsorship: "Educational institution issues I-20 form",
      dependents: "F-2 visa for spouse and unmarried children under 21",
    },
    {
      type: "J-1",
      name: "Exchange Visitors",
      description: "For educational and cultural exchange programs",
      duration: "Depends on program, typically 1-5 years",
      sponsorship: "Designated sponsor organization",
      dependents: "J-2 visa for spouse and unmarried children under 21",
    },
    {
      type: "M-1",
      name: "Vocational Students",
      description: "For students attending vocational or non-academic programs",
      duration: "Length of program, up to 1 year",
      sponsorship: "Educational institution issues I-20 form",
      dependents: "M-2 visa for spouse and unmarried children under 21",
    },
    {
      type: "F-1 OPT",
      name: "Optional Practical Training",
      description: "Work authorization for F-1 students after completion of studies",
      duration: "12 months (up to 36 months for STEM graduates)",
      sponsorship: "Educational institution recommendation, USCIS approval",
      dependents: "F-2 visa holders cannot work",
    },
    {
      type: "J-1 Academic Training",
      name: "Academic Training for J-1 Students",
      description: "Work authorization for J-1 students related to their field of study",
      duration: "Up to 18 months (36 months for postdoctoral training)",
      sponsorship: "J-1 program sponsor approval",
      dependents: "J-2 visa holders may apply for work authorization",
    },
  ],
  permanent: [
    {
      type: "EB-1",
      name: "Priority Workers",
      description:
        "For persons of extraordinary ability, outstanding professors/researchers, and multinational executives",
      duration: "Permanent (Green Card)",
      sponsorship: "Employer petition (sometimes self-petition for extraordinary ability)",
      dependents: "Spouse and unmarried children under 21 included",
    },
    {
      type: "EB-2",
      name: "Advanced Degree Professionals",
      description: "For professionals with advanced degrees or exceptional ability",
      duration: "Permanent (Green Card)",
      sponsorship: "Employer petition (sometimes self-petition with National Interest Waiver)",
      dependents: "Spouse and unmarried children under 21 included",
    },
    {
      type: "EB-3",
      name: "Skilled Workers and Professionals",
      description: "For skilled workers, professionals, and unskilled workers",
      duration: "Permanent (Green Card)",
      sponsorship: "Employer petition",
      dependents: "Spouse and unmarried children under 21 included",
    },
    {
      type: "EB-4",
      name: "Special Immigrants",
      description: "For religious workers, certain government employees, and other special categories",
      duration: "Permanent (Green Card)",
      sponsorship: "Varies by subcategory",
      dependents: "Spouse and unmarried children under 21 included",
    },
    {
      type: "EB-5",
      name: "Immigrant Investors",
      description: "For investors who invest $1.8 million ($900,000 in targeted employment areas)",
      duration: "Conditional permanent residence for 2 years, then permanent",
      sponsorship: "Self-petition",
      dependents: "Spouse and unmarried children under 21 included",
    },
    {
      type: "DV",
      name: "Diversity Visa (Lottery)",
      description: "Random selection of immigrants from countries with low immigration rates to the US",
      duration: "Permanent (Green Card)",
      sponsorship: "Self-application through lottery system",
      dependents: "Spouse and unmarried children under 21 included",
    },
    {
      type: "IR/CR",
      name: "Immediate Relatives of US Citizens",
      description: "For spouses, unmarried children under 21, and parents of US citizens",
      duration: "Permanent (Green Card)",
      sponsorship: "US citizen family member petition",
      dependents: "Direct beneficiaries only",
    },
    {
      type: "Family Preference",
      name: "Family-Sponsored Preferences",
      description: "For specific family relationships to US citizens and permanent residents",
      duration: "Permanent (Green Card)",
      sponsorship: "US citizen or permanent resident family member petition",
      dependents: "Spouse and unmarried children under 21 included",
    },
  ],
  other: [
    {
      type: "K-1",
      name: "Fiancé(e) Visa",
      description: "For fiancé(e)s of US citizens to enter US for marriage",
      duration: "90 days to marry, then adjust status",
      sponsorship: "US citizen petition",
      dependents: "K-2 visa for children of K-1 visa holder",
    },
    {
      type: "U",
      name: "Victims of Criminal Activity",
      description: "For victims of certain crimes who have suffered mental or physical abuse",
      duration: "4 years, may apply for green card after 3 years",
      sponsorship: "Law enforcement certification and USCIS petition",
      dependents: "Qualifying family members may receive derivative U visas",
    },
    {
      type: "T",
      name: "Victims of Human Trafficking",
      description: "For victims of human trafficking",
      duration: "4 years, may apply for green card after 3 years",
      sponsorship: "Self-petition with law enforcement cooperation",
      dependents: "Certain family members may receive derivative T visas",
    },
    {
      type: "TPS",
      name: "Temporary Protected Status",
      description: "For nationals of designated countries facing ongoing armed conflict or disasters",
      duration: "Varies by country designation, renewable",
      sponsorship: "Self-application if eligible by country",
      dependents: "Each family member must apply individually",
    },
    {
      type: "DACA",
      name: "Deferred Action for Childhood Arrivals",
      description: "For certain people who came to the US as children",
      duration: "2 years, renewable",
      sponsorship: "Self-application if meeting requirements",
      dependents: "No derivative status for family members",
    },
    {
      type: "A",
      name: "Diplomatic and Government Officials",
      description: "For diplomats, government officials, and their staff",
      duration: "Duration of assignment",
      sponsorship: "Government entity",
      dependents: "A visa for immediate family members",
    },
    {
      type: "G",
      name: "International Organization Representatives",
      description: "For representatives to international organizations like the UN",
      duration: "Duration of assignment",
      sponsorship: "International organization",
      dependents: "G visa for immediate family members",
    },
    {
      type: "NATO",
      name: "NATO Personnel",
      description: "For NATO representatives, officials, and experts",
      duration: "Duration of NATO assignment",
      sponsorship: "NATO organization",
      dependents: "NATO visa for immediate family members",
    },
  ],
}

// Platform-specific search string formats
const platformFormats = {
  linkedin: {
    name: "LinkedIn",
    description: "Professional social network",
    example: '(skill1 OR skill2) AND ("Java Developer" OR "Software Engineer") AND (experience OR senior)',
    tips: [
      "Use parentheses to group search terms",
      "Use quotation marks for exact phrases",
      "LinkedIn has a character limit for search strings",
    ],
  },
  indeed: {
    name: "Indeed",
    description: "Job search engine",
    example: 'title:("software engineer" OR "software developer") AND (java OR python)',
    tips: [
      "Use title: to search in job titles",
      "Use company: to search for specific companies",
      "Use location: for geographic searches",
    ],
  },
  dice: {
    name: "Dice",
    description: "Tech job board",
    example: '("software engineer" OR "software developer") AND (java OR python OR "machine learning")',
    tips: [
      "Dice supports standard Boolean operators (AND, OR, NOT)",
      "Use exact match with quotation marks for multi-word terms",
      "Dice works best with technical skills clearly separated",
      "Dice allows for proximity searches using ~N (e.g., 'java~5 developer')",
    ],
  },
  monster: {
    name: "Monster",
    description: "Job board",
    example: 'java AND (senior OR lead) AND "software engineer"',
    tips: ["Use AND between terms that must be included", "Use OR for alternatives", "Use NOT to exclude terms"],
  },
}

// US States information for interactive map
const statesInfo = {
  AL: {
    name: "Alabama",
    population: "5.03 million",
    timezone: "Central Time (CT)",
    culture: "Southern hospitality, rich history, college football",
    topCompanies: ["Regions Financial", "Vulcan Materials", "Encompass Health", "Protective Life", "BBVA USA"],
    demographics: "Diverse workforce with strengths in manufacturing and aerospace",
    description:
      "Alabama has a growing automotive and aerospace industry with Mercedes-Benz, Honda, and Hyundai manufacturing facilities. The state offers a lower cost of living compared to national averages.",
  },
  AK: {
    name: "Alaska",
    population: "731,545",
    timezone: "Alaska Time (AKT)",
    culture: "Outdoor lifestyle, indigenous heritage, independent spirit",
    topCompanies: ["Alaska Air Group", "GCI", "ASRC", "Alyeska Pipeline", "Chugach Alaska"],
    demographics: "Diverse population including significant Alaska Native communities",
    description:
      "Alaska's economy is heavily influenced by the oil, gas, and fishing industries. The state has unique recruitment challenges due to its remote location but offers high wages to compensate.",
  },
  AZ: {
    name: "Arizona",
    population: "7.28 million",
    timezone: "Mountain Time (MT) - no daylight saving time",
    culture: "Southwestern lifestyle, outdoor recreation, diverse communities",
    topCompanies: ["Banner Health", "Intel", "Raytheon", "Arizona State University", "Honeywell"],
    demographics: "Growing tech hub with significant Hispanic population",
    description:
      "Arizona has become a major tech and semiconductor manufacturing hub. Phoenix is experiencing rapid growth in technology jobs, while Tucson has strengths in aerospace and defense.",
  },
  AR: {
    name: "Arkansas",
    population: "3.01 million",
    timezone: "Central Time (CT)",
    culture: "Southern traditions, outdoor activities, community-focused",
    topCompanies: ["Walmart", "Tyson Foods", "J.B. Hunt", "Murphy USA", "Dillard's"],
    demographics: "Rural and small-city workforce with manufacturing expertise",
    description:
      "Arkansas is home to Walmart's headquarters in Bentonville, creating a retail and logistics hub. The state has a low cost of living and business-friendly environment.",
  },
  CA: {
    name: "California",
    population: "39.5 million",
    timezone: "Pacific Time (PT)",
    culture: "Diverse, tech-focused, entertainment hub",
    topCompanies: ["Apple", "Google", "Meta", "Disney", "Salesforce"],
    demographics: "Highly diverse population with significant tech talent",
    description:
      "California is known for Silicon Valley, Hollywood, and its diverse culture. It's the tech hub of the US with major companies headquartered in the Bay Area and Los Angeles.",
  },
  CO: {
    name: "Colorado",
    population: "5.77 million",
    timezone: "Mountain Time (MT)",
    culture: "Outdoor lifestyle, tech innovation, work-life balance",
    topCompanies: ["Arrow Electronics", "DaVita", "Ball Corporation", "Dish Network", "Newmont Mining"],
    demographics: "Highly educated workforce with tech and aerospace expertise",
    description:
      "Colorado has a thriving tech scene in Denver and Boulder. The state attracts talent with its outdoor lifestyle, growing tech sector, and aerospace industry.",
  },
  CT: {
    name: "Connecticut",
    population: "3.57 million",
    timezone: "Eastern Time (ET)",
    culture: "New England traditions, education focus, suburban lifestyle",
    topCompanies: ["General Electric", "Aetna", "Cigna", "United Technologies", "The Hartford"],
    demographics: "Highly educated workforce with finance and insurance expertise",
    description:
      "Connecticut has strengths in insurance, finance, and defense manufacturing. The state offers proximity to New York City while maintaining a suburban environment.",
  },
  DE: {
    name: "Delaware",
    population: "973,764",
    timezone: "Eastern Time (ET)",
    culture: "Business-friendly, coastal activities, small-town feel",
    topCompanies: ["DuPont", "ChristianaCare", "Bank of America", "JPMorgan Chase", "AstraZeneca"],
    demographics: "Diverse workforce with financial services expertise",
    description:
      "Delaware is known for its business-friendly corporate laws and financial services sector. Many companies incorporate in Delaware due to favorable business regulations.",
  },
  FL: {
    name: "Florida",
    population: "21.5 million",
    timezone: "Eastern Time (ET) & Central Time (CT)",
    culture: "Tourism-focused, retirement destination, Latin influence",
    topCompanies: ["Disney", "Universal", "Publix", "NextEra Energy", "Carnival Cruise"],
    demographics: "Diverse population with significant Hispanic communities",
    description:
      "Florida's economy is driven by tourism, agriculture, and aerospace. It's home to major theme parks and has a strong Latin American influence, especially in Miami.",
  },
  GA: {
    name: "Georgia",
    population: "10.6 million",
    timezone: "Eastern Time (ET)",
    culture: "Southern hospitality, growing tech scene, film industry",
    topCompanies: ["Home Depot", "UPS", "Coca-Cola", "Delta Air Lines", "Southern Company"],
    demographics: "Diverse workforce with significant African American population",
    description:
      "Georgia, particularly Atlanta, has become a major business hub in the Southeast. The state has a growing film industry and tech sector, with many corporate headquarters.",
  },
  HI: {
    name: "Hawaii",
    population: "1.42 million",
    timezone: "Hawaii-Aleutian Time (HAT)",
    culture: "Polynesian heritage, tourism industry, island lifestyle",
    topCompanies: ["Hawaiian Airlines", "Bank of Hawaii", "Hawaiian Electric", "Alexander & Baldwin", "Matson"],
    demographics: "Diverse multicultural population with Asian and Pacific Islander heritage",
    description:
      "Hawaii's economy is dominated by tourism, defense, and agriculture. The state offers a unique work environment but has a high cost of living compared to mainland states.",
  },
  ID: {
    name: "Idaho",
    population: "1.79 million",
    timezone: "Mountain Time (MT) & Pacific Time (PT)",
    culture: "Outdoor recreation, agricultural heritage, growing tech presence",
    topCompanies: ["Micron Technology", "Albertsons", "Idaho Power", "Simplot", "WinCo Foods"],
    demographics: "Growing population with tech and agricultural expertise",
    description:
      "Idaho has a growing tech sector, particularly in Boise. The state is known for semiconductor manufacturing, agriculture, and outdoor recreation industries.",
  },
  IL: {
    name: "Illinois",
    population: "12.7 million",
    timezone: "Central Time (CT)",
    culture: "Midwestern values, diverse urban center in Chicago",
    topCompanies: ["Boeing", "McDonald's", "Walgreens", "Allstate", "Caterpillar"],
    demographics: "Diverse workforce with strengths in finance, manufacturing, and transportation",
    description:
      "Illinois is a transportation hub with Chicago being a major financial center. It has diverse industries including manufacturing, finance, and agriculture.",
  },
  IN: {
    name: "Indiana",
    population: "6.73 million",
    timezone: "Eastern Time (ET) & Central Time (CT)",
    culture: "Midwestern values, manufacturing heritage, sports enthusiasm",
    topCompanies: ["Eli Lilly", "Cummins", "Anthem", "Steel Dynamics", "NiSource"],
    demographics: "Manufacturing-oriented workforce with growing life sciences sector",
    description:
      "Indiana has a strong manufacturing base, particularly in automotive and medical devices. The state also has a growing life sciences and technology sector.",
  },
  IA: {
    name: "Iowa",
    population: "3.16 million",
    timezone: "Central Time (CT)",
    culture: "Agricultural heritage, education focus, community-oriented",
    topCompanies: ["Principal Financial", "Casey's General Stores", "Rockwell Collins", "Hy-Vee", "Vermeer"],
    demographics: "Rural and small-city workforce with agricultural expertise",
    description:
      "Iowa has strengths in agriculture, manufacturing, and financial services. The state offers a low cost of living and strong educational institutions.",
  },
  KS: {
    name: "Kansas",
    population: "2.91 million",
    timezone: "Central Time (CT) & Mountain Time (MT)",
    culture: "Midwestern values, agricultural heritage, aerospace industry",
    topCompanies: ["Spirit AeroSystems", "Garmin", "Sprint", "Cargill Meat Solutions", "Koch Industries"],
    demographics: "Mix of rural agricultural and urban manufacturing workforce",
    description:
      "Kansas has a diverse economy with strengths in aerospace manufacturing, agriculture, and energy. Wichita is known as the 'Air Capital of the World' due to its aircraft manufacturing.",
  },
  KY: {
    name: "Kentucky",
    population: "4.47 million",
    timezone: "Eastern Time (ET) & Central Time (CT)",
    culture: "Southern hospitality, bourbon heritage, horse racing",
    topCompanies: ["Humana", "Yum! Brands", "Brown-Forman", "Lexmark", "Toyota Motor Manufacturing"],
    demographics: "Manufacturing and healthcare-oriented workforce",
    description:
      "Kentucky has strengths in automotive manufacturing, healthcare, and logistics. The state is home to UPS's Worldport, the company's largest air hub.",
  },
  LA: {
    name: "Louisiana",
    population: "4.65 million",
    timezone: "Central Time (CT)",
    culture: "Creole and Cajun heritage, music scene, culinary traditions",
    topCompanies: ["Entergy", "CenturyLink", "Ochsner Health System", "Shaw Group", "Lamar Advertising"],
    demographics: "Diverse workforce with energy and tourism expertise",
    description:
      "Louisiana's economy is heavily influenced by the oil and gas industry, shipping, and tourism. New Orleans is a major port and cultural center.",
  },
  ME: {
    name: "Maine",
    population: "1.34 million",
    timezone: "Eastern Time (ET)",
    culture: "New England traditions, outdoor lifestyle, coastal communities",
    topCompanies: ["L.L. Bean", "IDEXX Laboratories", "WEX", "Jackson Laboratory", "MaineHealth"],
    demographics: "Aging workforce with healthcare and tourism expertise",
    description:
      "Maine has strengths in healthcare, tourism, and marine industries. The state offers quality of life benefits but faces challenges with an aging workforce.",
  },
  MD: {
    name: "Maryland",
    population: "6.05 million",
    timezone: "Eastern Time (ET)",
    culture: "Mid-Atlantic blend, government and defense focus, diverse communities",
    topCompanies: ["Lockheed Martin", "Marriott International", "T. Rowe Price", "McCormick & Company", "Under Armour"],
    demographics: "Highly educated workforce with government and defense expertise",
    description:
      "Maryland has a strong presence in biotechnology, cybersecurity, and defense. The state benefits from proximity to Washington D.C. and federal agencies.",
  },
  MA: {
    name: "Massachusetts",
    population: "6.89 million",
    timezone: "Eastern Time (ET)",
    culture: "Education focus, innovation hub, New England traditions",
    topCompanies: ["General Electric", "Raytheon", "Biogen", "State Street", "TJX Companies"],
    demographics: "Highly educated workforce with technology and life sciences expertise",
    description:
      "Massachusetts is a leader in education, biotechnology, and finance. Boston is a major innovation hub with prestigious universities and a thriving startup ecosystem.",
  },
  MI: {
    name: "Michigan",
    population: "9.99 million",
    timezone: "Eastern Time (ET) & Central Time (CT)",
    culture: "Automotive heritage, Great Lakes lifestyle, manufacturing tradition",
    topCompanies: ["General Motors", "Ford", "Dow Chemical", "Whirlpool", "Stryker"],
    demographics: "Manufacturing-oriented workforce with engineering expertise",
    description:
      "Michigan is the center of the U.S. automotive industry. The state is experiencing growth in technology and advanced manufacturing sectors, particularly in Detroit and Ann Arbor.",
  },
  MN: {
    name: "Minnesota",
    population: "5.64 million",
    timezone: "Central Time (CT)",
    culture: "Scandinavian influence, outdoor activities, progressive values",
    topCompanies: ["UnitedHealth Group", "Target", "Best Buy", "3M", "Medtronic"],
    demographics: "Highly educated workforce with healthcare and retail expertise",
    description:
      "Minnesota has a diverse economy with strengths in healthcare, retail, and manufacturing. The Twin Cities area is home to many Fortune 500 companies.",
  },
  MS: {
    name: "Mississippi",
    population: "2.98 million",
    timezone: "Central Time (CT)",
    culture: "Southern traditions, musical heritage, rural communities",
    topCompanies: ["Sanderson Farms", "Ergon", "Hancock Whitney", "Cal-Maine Foods", "Trustmark"],
    demographics: "Manufacturing and agricultural workforce",
    description:
      "Mississippi has strengths in manufacturing, agriculture, and shipbuilding. The state offers a low cost of living and business-friendly environment.",
  },
  MO: {
    name: "Missouri",
    population: "6.14 million",
    timezone: "Central Time (CT)",
    culture: "Midwestern values, diverse urban centers, agricultural heritage",
    topCompanies: ["Centene", "Emerson Electric", "Express Scripts", "Monsanto", "O'Reilly Automotive"],
    demographics: "Diverse workforce with manufacturing and healthcare expertise",
    description:
      "Missouri has a diverse economy with strengths in aerospace, biotechnology, and agriculture. St. Louis and Kansas City are major business centers.",
  },
  MT: {
    name: "Montana",
    population: "1.07 million",
    timezone: "Mountain Time (MT)",
    culture: "Outdoor lifestyle, western heritage, independent spirit",
    topCompanies: ["Glacier Bancorp", "Washington Companies", "Stillwater Mining", "First Interstate BancSystem", "Oracle"],
    demographics: "Rural workforce with natural resources and tourism expertise",
    description:
      "Montana's economy includes agriculture, tourism, and natural resource extraction. The state is seeing growth in technology sectors, particularly in Bozeman.",
  },
  NE: {
    name: "Nebraska",
    population: "1.93 million",
    timezone: "Central Time (CT) & Mountain Time (MT)",
    culture: "Midwestern values, agricultural heritage, community-oriented",
    topCompanies: ["Berkshire Hathaway", "Union Pacific", "Peter Kiewit Sons'", "Mutual of Omaha", "ConAgra Foods"],
    demographics: "Agricultural and financial services workforce",
    description:
      "Nebraska has strengths in agriculture, insurance, and transportation. Omaha is a major center for the insurance industry and home to Berkshire Hathaway.",
  },
  NV: {
    name: "Nevada",
    population: "3.08 million",
    timezone: "Pacific Time (PT) & Mountain Time (MT)",
    culture: "Entertainment focus, desert lifestyle, tourism industry",
    topCompanies: ["Las Vegas Sands", "MGM Resorts", "Caesars Entertainment", "Wynn Resorts", "Switch"],
    demographics: "Service industry workforce with hospitality expertise",
    description:
      "Nevada's economy is dominated by tourism, gaming, and mining. The state is diversifying with growth in technology and manufacturing sectors.",
  },
  NH: {
    name: "New Hampshire",
    population: "1.36 million",
    timezone: "Eastern Time (ET)",
    culture: "New England traditions, independent spirit, outdoor recreation",
    topCompanies: ["Dartmouth-Hitchcock", "BAE Systems", "Hypertherm", "Timberland", "Sig Sauer"],
    demographics: "Highly educated workforce with manufacturing and healthcare expertise",
    description:
      "New Hampshire has no income or sales tax, making it attractive for businesses. The state has strengths in advanced manufacturing, healthcare, and technology.",
  },
  NJ: {
    name: "New Jersey",
    population: "8.88 million",
    timezone: "Eastern Time (ET)",
    culture: "Diverse communities, pharmaceutical industry, suburban lifestyle",
    topCompanies: ["Johnson & Johnson", "Prudential Financial", "Merck", "Honeywell", "BD"],
    demographics: "Highly educated workforce with pharmaceutical and financial expertise",
    description:
      "New Jersey is a leader in pharmaceuticals, telecommunications, and food processing. The state offers proximity to New York City and Philadelphia.",
  },
  NM: {
    name: "New Mexico",
    population: "2.10 million",
    timezone: "Mountain Time (MT)",
    culture: "Hispanic and Native American heritage, artistic communities, desert lifestyle",
    topCompanies: ["Los Alamos National Laboratory", "Sandia National Laboratories", "Presbyterian Healthcare", "Intel", "Public Service Company of New Mexico"],
    demographics: "Diverse workforce with government and energy expertise",
    description:
      "New Mexico has strengths in energy, research, and aerospace. The state is home to major national laboratories and a growing film industry.",
  },
  NY: {
    name: "New York",
    population: "19.8 million",
    timezone: "Eastern Time (ET)",
    culture: "Fast-paced, financial center, arts hub",
    topCompanies: ["JPMorgan Chase", "IBM", "Citigroup", "Goldman Sachs", "Pfizer"],
    demographics: "Diverse workforce with financial and media expertise",
    description:
      "New York is the financial capital of the US with Wall Street in Manhattan. It's also a center for media, advertising, and fashion industries.",
  },
  NC: {
    name: "North Carolina",
    population: "10.5 million",
    timezone: "Eastern Time (ET)",
    culture: "Southern hospitality, research focus, diverse geography",
    topCompanies: ["Bank of America", "Duke Energy", "Lowe's", "Nucor", "Laboratory Corp. of America"],
    demographics: "Diverse workforce with banking, research, and manufacturing expertise",
    description:
      "North Carolina has a strong presence in banking, research, and technology. The Research Triangle Park is a major center for technology and pharmaceutical companies.",
  },
  ND: {
    name: "North Dakota",
    population: "762,062",
    timezone: "Central Time (CT) & Mountain Time (MT)",
    culture: "Agricultural heritage, energy industry, community-oriented",
    topCompanies: ["MDU Resources", "Scheels", "Bobcat Company", "Aldevron", "Border States Electric"],
    demographics: "Energy and agricultural workforce",
    description:
      "North Dakota has experienced growth due to oil and natural gas development. The state has a low unemployment rate and strengths in agriculture and energy.",
  },
  OH: {
    name: "Ohio",
    population: "11.7 million",
    timezone: "Eastern Time (ET)",
    culture: "Midwestern values, manufacturing heritage, diverse urban centers",
    topCompanies: ["Procter & Gamble", "Kroger", "Marathon Petroleum", "Cardinal Health", "Progressive"],
    demographics: "Manufacturing-oriented workforce with diverse industry expertise",
    description:
      "Ohio has a diverse economy with strengths in manufacturing, healthcare, and financial services. The state is home to major corporations and research institutions.",
  },
  OK: {
    name: "Oklahoma",
    population: "3.96 million",
    timezone: "Central Time (CT)",
    culture: "Native American heritage, energy industry, southern influence",
    topCompanies: ["Devon Energy", "Chesapeake Energy", "Continental Resources", "Williams Companies", "ONEOK"],
    demographics: "Energy and agricultural workforce",
    description:
      "Oklahoma's economy is heavily influenced by the oil and gas industry. The state also has strengths in aerospace, agriculture, and biotechnology.",
  },
  OR: {
    name: "Oregon",
    population: "4.22 million",
    timezone: "Pacific Time (PT) & Mountain Time (MT)",
    culture: "Outdoor lifestyle, environmental focus, tech industry",
    topCompanies: ["Nike", "Intel", "Columbia Sportswear", "Precision Castparts", "Lithia Motors"],
    demographics: "Tech-oriented workforce with manufacturing and outdoor industry expertise",
    description:
      "Oregon has strengths in technology, sportswear, and agriculture. Portland has become a hub for technology companies and startups.",
  },
  PA: {
    name: "Pennsylvania",
    population: "12.8 million",
    timezone: "Eastern Time (ET)",
    culture: "Industrial heritage, diverse urban and rural communities",
    topCompanies: ["Comcast", "AmerisourceBergen", "Rite Aid", "PNC Financial Services", "PPG Industries"],
    demographics: "Diverse workforce with manufacturing, healthcare, and financial expertise",
    description:
      "Pennsylvania has a diverse economy with strengths in manufacturing, healthcare, and financial services. Philadelphia and Pittsburgh are major business centers.",
  },
  RI: {
    name: "Rhode Island",
    population: "1.06 million",
    timezone: "Eastern Time (ET)",
    culture: "New England traditions, coastal communities, education focus",
    topCompanies: ["CVS Health", "Textron", "Citizens Financial Group", "Hasbro", "United Natural Foods"],
    demographics: "Healthcare and education-oriented workforce",
    description:
      "Rhode Island has strengths in healthcare, education, and maritime industries. The state offers quality of life benefits and proximity to Boston.",
  },
  SC: {
    name: "South Carolina",
    population: "5.15 million",
    timezone: "Eastern Time (ET)",
    culture: "Southern hospitality, coastal tourism, manufacturing growth",
    topCompanies: ["Boeing", "BMW Manufacturing", "Michelin", "Sonoco", "SCANA"],
    demographics: "Manufacturing and tourism workforce",
    description:
      "South Carolina has seen growth in automotive and aerospace manufacturing. The state offers a business-friendly environment and quality of life benefits.",
  },
  SD: {
    name: "South Dakota",
    population: "884,659",
    timezone: "Central Time (CT) & Mountain Time (MT)",
    culture: "Rural lifestyle, Native American heritage, agricultural focus",
    topCompanies: ["Sanford Health", "Citibank", "Daktronics", "Black Hills Corporation", "Raven Industries"],
    demographics: "Agricultural and financial services workforce",
    description:
      "South Dakota has strengths in agriculture, financial services, and healthcare. The state has no corporate income tax, making it attractive for businesses.",
  },
  TN: {
    name: "Tennessee",
    population: "6.83 million",
    timezone: "Eastern Time (ET) & Central Time (CT)",
    culture: "Music heritage, southern hospitality, diverse geography",
    topCompanies: ["FedEx", "HCA Healthcare", "Dollar General", "AutoZone", "International Paper"],
    demographics: "Diverse workforce with logistics, healthcare, and music industry expertise",
    description:
      "Tennessee has strengths in logistics, healthcare, and automotive manufacturing. Nashville is a major center for the healthcare and music industries.",
  },
  TX: {
    name: "Texas",
    population: "29.1 million",
    timezone: "Central Time (CT) & Mountain Time (MT)",
    culture: "Southern hospitality, independent spirit",
    topCompanies: ["Dell", "ExxonMobil", "AT&T", "Texas Instruments", "USAA"],
    demographics: "Diverse workforce with energy, technology, and healthcare expertise",
    description:
      "Texas has a strong economy with major industries in energy, technology, and healthcare. Austin has emerged as a major tech hub, often called 'Silicon Hills'.",
  },
  UT: {
    name: "Utah",
    population: "3.21 million",
    timezone: "Mountain Time (MT)",
    culture: "Outdoor lifestyle, family-oriented, tech growth",
    topCompanies: ["Zions Bancorporation", "Huntsman", "SkyWest Airlines", "Merit Medical Systems", "Qualtrics"],
    demographics: "Young, educated workforce with technology expertise",
    description:
      "Utah has a rapidly growing technology sector, particularly in the 'Silicon Slopes' area. The state offers outdoor recreation and a business-friendly environment.",
  },
  VT: {
    name: "Vermont",
    population: "623,989",
    timezone: "Eastern Time (ET)",
    culture: "New England traditions, environmental focus, rural lifestyle",
    topCompanies: ["Keurig Dr Pepper", "Ben & Jerry's", "National Life Group", "Casella Waste Systems", "Dealer.com"],
    demographics: "Tourism and agricultural workforce",
    description:
      "Vermont has strengths in tourism, agriculture, and manufacturing. The state is known for its quality of life and environmental focus.",
  },
  VA: {
    name: "Virginia",
    population: "8.54 million",
    timezone: "Eastern Time (ET)",
    culture: "Southern traditions, government and defense focus, diverse communities",
    topCompanies: ["Capital One", "General Dynamics", "Northrop Grumman", "Dollar Tree", "AES"],
    demographics: "Highly educated workforce with government, defense, and technology expertise",
    description:
      "Virginia has a strong presence in defense, technology, and government contracting. Northern Virginia is part of the Washington D.C. metropolitan area.",
  },
  WA: {
    name: "Washington",
    population: "7.61 million",
    timezone: "Pacific Time (PT)",
    culture: "Tech industry, outdoor lifestyle, environmental focus",
    topCompanies: ["Amazon", "Microsoft", "Boeing", "Starbucks", "Costco"],
    demographics: "Tech-oriented workforce with aerospace and retail expertise",
    description:
      "Washington is home to major technology companies and aerospace manufacturing. Seattle is a major tech hub with Amazon and Microsoft headquartered in the area.",
  },
  WV: {
    name: "West Virginia",
    population: "1.79 million",
    timezone: "Eastern Time (ET)",
    culture: "Appalachian heritage, coal mining history, outdoor recreation",
    topCompanies: ["West Virginia United Health System", "Mylan Pharmaceuticals", "Kroger", "Camcare", "Toyota Motor Manufacturing"],
    demographics: "Energy and healthcare workforce",
    description:
      "West Virginia has strengths in energy, healthcare, and tourism. The state is working to diversify its economy beyond coal mining.",
  },
  WI: {
    name: "Wisconsin",
    population: "5.82 million",
    timezone: "Central Time (CT)",
    culture: "Midwestern values, manufacturing heritage, outdoor recreation",
    topCompanies: ["Northwestern Mutual", "Johnson Controls", "Kohl's", "Harley-Davidson", "Oshkosh Corporation"],
    demographics: "Manufacturing-oriented workforce with agricultural expertise",
    description:
      "Wisconsin has strengths in manufacturing, agriculture, and healthcare. The state is known for its dairy industry and manufacturing innovation.",
  },
  WY: {
    name: "Wyoming",
    population: "578,759",
    timezone: "Mountain Time (MT)",
    culture: "Western heritage, outdoor lifestyle, energy industry",
    topCompanies: ["Cloud Peak Energy", \"Wyoming\"];\
